databases:
  - name: railsban
    databaseName: railsban
    user: railsban

services:
  - type: web
    name: railsban
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: railsban
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false